<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>FERRETERIA__Joel.Aplicacion</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FERRETERIA__Joel.Dominio\FERRETERIA__Joel.Dominio.csproj" />
  </ItemGroup>

</Project>
