<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>FERRETERIA__Joel</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="26.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FERRETERIA__Joel.Dominio\FERRETERIA__Joel.Dominio.csproj" />
    <ProjectReference Include="..\FERRETERIA__Joel.Aplicacion\FERRETERIA__Joel.Aplicacion.csproj" />
    <ProjectReference Include="..\FERRETERIA__Joel.Infraestructura\FERRETERIA__Joel.Infraestructura.csproj" />
  </ItemGroup>

</Project>
